# .github/workflows/actionlint.yml
name: Lint GitHub Actions workflows

on:
  pull_request:
    paths:
      - .github/workflows/*.yml
      - .github/workflows/*.yaml
  push:
    paths:
      - .github/workflows/*.yml
      - .github/workflows/*.yaml

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-review
