name: Check uv sync

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  uv:
    name: uv sync
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version-file: ".python-version"
          # activate-environment: true
          # enable-cache: true

      - name: Check uv.lock sync
        run: uv sync --locked

      - name: Minimize uv cache
        run: uv cache prune --ci
